export const {
    APP_NAME,
    IPBIND = '127.0.0.1',
    PORT = 4000,
    AUTH_URL,
    DATABASE_URL,
    JWT_SECRET,
    JWT_ACCESS_EXPIRATION = '1h',
    JWT_REFRESH_EXPIRATION = '6h',
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    CAPTCHA_PROVIDER,
    CAPTCHA_SECRET,
    SIZE_LIMIT = '10MB',
} = Bun.env;

export const ALLOW_REGISTER_SERVICE =
    Bun.env.ALLOW_REGISTER_SERVICE === 'true';
